obj-$(CONFIG_MSM_DBA) += msm_dba.o msm_dba_init.o msm_dba_helpers.o msm_dba_debug.o
obj-$(CONFIG_MSM_DBA_ADV7533) += adv7533.o ddcci_i2c.o
obj-$(CONFIG_SN65DSI86_DSI_TO_EDP) += sn65dsi86_dsi2edp.o
obj-$(CONFIG_SN65DSI86_DSI_TO_EDP) += sn65dsi85_dsi2lvds.o
clean:
	rm *.o
